import MySQLdb

db = MySQLdb.connect(user="root", passwd="root", db="treinaweb_clientes", host="localhost", port=3306)
cursor = db.cursor()
cursor.execute("SELECT * FROM cliente")
print(cursor.fetchall())
print("Conexão realizada com sucesso")
cursor.execute("INSERT INTO cliente (nome, idade) VALUES ('Maria', 25)")
cursor.execute("SELECT * FROM cliente")
print(cursor.fetchall())
print(cursor.lastrowid)
cursor.execute("UPDATE cliente SET nome='Ana' WHERE idcliente=2")
cursor.execute("SELECT * FROM cliente")
print(cursor.fetchall())
cursor.execute("DELETE FROM cliente WHERE idcliente=2")
cursor.execute("SELECT * FROM cliente")
print(cursor.fetchall())
db.close()